package com.edgn.uifw.css;

public enum StyleKey {

    PRIMARY, SECONDARY, SUCCESS, DANGER, WARNING, INFO, LIGHT, DARK,
    SURFACE, BACKGROUND, ACCENT, MUTED, GLASS, NEON,
    PRIMARY_LIGHT, PRIMARY_DARK, SUCCESS_LIGHT, DANGER_LIGHT,

    BG_PRIMARY, BG_SECONDARY, BG_SUCCESS, BG_DANGER, BG_WARNING, BG_INFO,
    BG_SURFACE, BG_BACKGROUND, BG_GLASS,

    BG_OPACITY_0, BG_OPACITY_1, BG_OPACITY_2, BG_OPACITY_3, BG_OPACITY_4, BG_OPACITY_5, BG_OPACITY_6, BG_OPACITY_7, BG_OPACITY_8,
    BG_OPACITY_9, BG_OPACITY_10, BG_OPACITY_11, BG_OPACITY_12, BG_OPACITY_13, BG_OPACITY_14, BG_OPACITY_15,

    TEXT_WHITE, TEXT_BLACK, TEXT_PRIMARY, TEXT_SECONDARY, TEXT_MUTED,

    HOVER_BRIGHTEN, HOVER_SCALE, HOVER_OPACITY, HOVER_ROTATE,
    FOCUS_RING, FOCUS_OUTLINE, ACTIVE_SCALE,

    ROUNDED_NONE, ROUNDED_SM, ROUNDED_MD, ROUNDED_LG, ROUNDED_XL, ROUNDED_XXL, ROUNDED_FULL,

    P_0, P_1, P_2, P_3, P_4, P_5,
    PT_0, PT_1, PT_2, PT_3, PT_4, PT_5, PT_6, PT_7, PT_8,
    PR_0, PR_1, PR_2, PR_3, PR_4, PR_5, PR_6, PR_7, PR_8,
    PB_0, PB_1, PB_2, PB_3, PB_4, PB_5, PB_6, PB_7, PB_8,
    PL_0, PL_1, PL_2, PL_3, PL_4, PL_5, PL_6, PL_7, PL_8,

    M_0, M_1, M_2, M_3, M_4, M_5,
    MT_0, MT_1, MT_2, MT_3, MT_4, MT_5, MT_6, MT_7, MT_8,
    MR_0, MR_1, MR_2, MR_3, MR_4, MR_5, MR_6, MR_7, MR_8,
    MB_0, MB_1, MB_2, MB_3, MB_4, MB_5, MB_6, MB_7, MB_8,
    ML_0, ML_1, ML_2, ML_3, ML_4, ML_5, ML_6, ML_7, ML_8,

    SHADOW_NONE, SHADOW_SM, SHADOW_MD, SHADOW_LG, SHADOW_XL, SHADOW_GLOW,

    FLEX_ROW, FLEX_COLUMN, FLEX_ROW_REVERSE, FLEX_COLUMN_REVERSE,
    FLEX_WRAP, FLEX_NOWRAP, FLEX_WRAP_REVERSE,
    JUSTIFY_START, JUSTIFY_CENTER, JUSTIFY_END, JUSTIFY_BETWEEN, JUSTIFY_AROUND, JUSTIFY_EVENLY,
    ITEMS_START, ITEMS_CENTER, ITEMS_END, ITEMS_STRETCH, ITEMS_BASELINE,

    FLEX_GROW_0, FLEX_GROW_1, FLEX_GROW_2, FLEX_GROW_3,
    FLEX_SHRINK_0, FLEX_SHRINK_1,

    GAP_0, GAP_1, GAP_2, GAP_3, GAP_4, GAP_5, GAP_6, GAP_8,
}